### ISSUE TITLE
Suggestion for Enhancement

### ISSUE THREAD

**Issue by Scoodood** [oivva/st-boxy#145]
Thanks for the great Theme. Please consider my feedback for future enhancement. I am using Sublime Text 3 Build 3126, OSX 10.10.5

1. The text from the text view almost touches the tab as seen on the picture below. The top margin of the text view is too small.
![screen shot 2016-11-04 at 1 28 45 pm](https://cloud.githubusercontent.com/assets/15989924/20021435/f0b20dd2-a292-11e6-96ab-61af7e598f49.png)

2. I find that the icons from [Afterglow Theme](http://yabatadesign.github.io/afterglow-theme/) very pleasant for viewing. It is not too **bold** to distract my attention, and it blends in really well.
![screen shot 2016-11-04 at 12 56 36 pm](https://cloud.githubusercontent.com/assets/15989924/20021632/facb8824-a293-11e6-9249-a0dde2b5f714.png) <br>
The icons from the Boxy Theme on the other hand, is too **attractive** to my liking.
![screen shot 2016-11-04 at 1 02 58 pm](https://cloud.githubusercontent.com/assets/15989924/20021687/3b24ff9a-a294-11e6-9bb9-6aa433eaa9d7.png)

Thank you very much

**Comment by oivva** [comment]
@Scoodood Thanks for your request.

1. Unfortunately it's not possible :disappointed: The same request is on the [ST Forum](https://forum.sublimetext.com/t/boxy-the-most-hackable-theme-for-sublime-text-3/20564/83).

2. Sorry, I don't want to provide another set of icons, because many users like current implementation. You can try [Boxy Theme Addon - Mono File Icons](https://packagecontrol.io/packages/Boxy%20Theme%20Addon%20-%20Mono%20File%20Icons) or [these options](https://github.com/oivva/st-boxy/wiki/Settings#sidebar-icons).
